import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import '../fonts/Poppins/stylesheet.css';
import { HeaderBar } from '@/components/HeaderBar';
import { FooterBar } from '@/components/FooterBar';
import { BasketProvider } from '@/context/BasketProvider';
import { UserProvider } from '@/context/UserProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>,
) {
  return (
    <html lang="en">
    <body>

    <UserProvider>
      <BasketProvider>
        <HeaderBar/>
        <main>
          {children}
        </main>
        <FooterBar/>
      </BasketProvider>
    </UserProvider>

    </body>
    </html>
  );
}
